//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyAccount
    {
        public int Sno { get; set; }
        public Nullable<long> FromAccount { get; set; }
        public Nullable<long> ToAccount { get; set; }
    }
}
